export const skillsData = [
  {
    title: "HTML",
    id: 1,
    main: "/skills/html.png",
    desc: "Hypertext Markup Language, or HTML, is a programming language used to describe the structure of web pages",
    tag: "web structure",
    bg: "bg-orange-600",
    text: "text-yellow-500",
  },
  {
    title: "CSS",
    id: 2,
    main: "/skills/css.svg",
    desc: "Cascading Style Sheets is a style sheet language used for specifying the presentation and styling",
    tag: "styling",
    bg: "bg-orange-700",
    text: "text-yellow-500",
  },
  
  {
    title: "JavaScript",
    id: 3,
    main: "/skills/javascript-original.svg",
    desc: "A lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
    tag: "multipurpose",
    bg: "bg-yellow-50",
    text: "text-yellow-500",
  },
  {
    title: "TypeScript",
    id: 4,
    main: "/skills/typescript-plain.svg",
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "language",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "React JS",
    id: 5,
    main: "/skills/react-original.svg",
    desc: "A free and open-source front-end JavaScript library for building user interfaces based on components",
    tag: "JS Libarary",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "Next JS",
    id: 6,
    main: "/skills/nextjs-original.svg",
    desc: "An open-source web development framework providing React-based web applications.",
    tag: "Framwork",
    bg: "bg-gray-900",
    text: "text-gray-50",
  },
  {
    title: "NodeJS",
    id: 7,
    main: "/skills/node.svg",
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "runtime enviroment",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "ExpressJS",
    id: 8,
    main: "/skills/express.png",
    desc: "o build a single page, multipage, and hybrid web application.",
    tag: "Framwork",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "mongoDB",
    id: 9,
    main: "/skills/mongo.png",
    desc: "makes it easy for developers to store, manage, and retrieve data ",
    tag: "Database",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "Tailwind CSS",
    id: 10,
    main: "/skills/tailwindcss-plain.svg",
    desc: "A utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    tag: "Styling",
    bg: "bg-green-50",
    text: "text-green-500",
  },
  {
    title: "Bootstrap",
    id: 11,
    main: "/skills/bootstrap-plain.svg",
    desc: "CSS with superpowers. The most powerful professional grade CSS extension language in the world.",
    tag: "design",
    bg: "bg-pink-300",
    text: "text-pink-800",
  },
  {
    title: "Redux/Redux-Toolkit",
    id: 12,
    main: "/skills/redux.svg",
    desc: "A boon for webapp designers, from wireframe to animation, it has it all.",
    tag: "state",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
  {
    title: "VS Code",
    id: 13,
    main: "/skills/vscode-original.svg",
    desc: "Best coding IDE to ever exist, comes with tons of customization",
    tag: "code editor",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
 
  {
    title: "Java",
    id: 14,
    main: "/skills/java.svg",
    desc: "It is a general-purpose programming language intended to let programmers write once.",
    tag: "programming",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
  {
    title: "Prisma",
    id: 15,
    main: "/skills/prisma.png",
    desc: "Preferred Reporting Items for Systematic reviews and Meta-Analyses",
    tag: "database toolkit",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
  {
    title: "Cypress/testing",
    id: 16,
    main: "/skills/cypress.svg",
    desc: "create tests for your modern web applications, debug them visually, and automatically.",
    tag: "testing",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
  {
    title: "Material UI",
    id: 17,
    main: "/skills/materialui-original.svg",
    desc: "A comprehensive suite of UI tools to help you ship new features faster.",
    tag: "develop",
    bg: "bg-indigo-50",
    text: "text-indigo-500",
  },
  {
    title: "GitHub",
    id: 18,
    main: "/skills/github-original.svg",
    desc: "A developer's go-to platform for collaborating and showcasing their code.",
    tag: "platform",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
  {
    title: "PostgreSQL",
    id: 19,
    main: "/skills/postgreSQL.png",
    desc: "Communicate with the database servers using objects in their code. Define complex custom data types",
    tag: "dbms",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
];
