export const skillsData = [
  {
    title: "VS Code",
    id: 0,
    main: "/icons/vscode-original.svg",
    desc: "Best coding IDE to ever exist, comes with tons of customization",
    tag: "code editor",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "JavaScript",
    id: 1,
    main: "/icons/javascript-original.svg",
    desc: "A lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
    tag: "multipurpose",
    bg: "bg-yellow-50",
    text: "text-yellow-500",
  },
  {
    title: "TypeScript",
    id: 2,
    main: "/icons/typescript-plain.svg",
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "language",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "React JS",
    id: 3,
    main: "/icons/react-original.svg",
    desc: "A free and open-source front-end JavaScript library for building user interfaces based on components",
    tag: "develop",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "Next JS",
    id: 4,
    main: "/icons/nextjs-original.svg",
    desc: "An open-source web development framework providing React-based web applications.",
    tag: "develop",
    bg: "bg-gray-900",
    text: "text-gray-50",
  },
  {
    title: "Tailwind CSS",
    id: 5,
    main: "/icons/tailwindcss-plain.svg",
    desc: "A utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    tag: "design",
    bg: "bg-green-50",
    text: "text-green-500",
  },
  {
    title: "Material UI",
    id: 6,
    main: "/icons/materialui-original.svg",
    desc: "A comprehensive suite of UI tools to help you ship new features faster.",
    tag: "develop",
    bg: "bg-indigo-50",
    text: "text-indigo-500",
  },
  {
    title: "Bootstrap",
    id: 7,
    main: "/icons/bootstrap-plain.svg",
    desc: "CSS with superpowers. The most powerful professional grade CSS extension language in the world.",
    tag: "design",
    bg: "bg-pink-300",
    text: "text-pink-800",
  },
  {
    title: "Java",
    id: 8,
    main: "/icons/java.svg",
    desc: "It is a general-purpose programming language intended to let programmers write once, run anywhere (WORA), meaning that compiled Java code can run on all platforms that support Java without the need to recompile. ",
    tag: "programming",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
  {
    title: "redux",
    id: 9,
    main: "/icons/redux.svg",
    desc: "A boon for webapp designers, from wireframe to animation, it has it all.",
    tag: "state",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
  {
    title: "GitHub",
    id: 10,
    main: "/icons/github-original.svg",
    desc: "A developer's go-to platform for collaborating and showcasing their code.",
    tag: "platform",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
  {
    title: "Brave",
    id: 11,
    main: "/brave-icon.svg",
    desc: "A privacy focused browser used to block ads and extra pops.",
    tag: "platform",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
];
